---
title: "Seurat and R Coding Training"
author: "Ryan"
date: "4/10/2020"
output: html_document
---

##Load Packages

```{r load.packages}
library(Seurat)
library(ggplot2)
library(dplyr)
```

##Load Seurat Objects

```{r load.object}
load("hci001.seurat3.object.Rda")
training.object <- p01.cc.updated
```

##Adding Information to Meta Data Columns

```{r adding.meta.data}
#  "@" accesses slots in the Seurat object
# "$" accesses rows in a matrix
training.object@meta.data$tissue[1:6]

#Create fake list of cells that are doublets
rownames(training.object@meta.data)[1:15]->doublets

# which() command searches for exact strings
# grep() searches for partial strings
which(rownames(training.object@meta.data) %in% doublets) -> doublet.rows
which(rownames(training.object@meta.data) %in% doublets)

grep("_I_", rownames(training.object@meta.data))

# adding meta.data
AddMetaData(training.object, metadata, col.name = "doubles")
training.object[["doublet.ID"]]<-metadata

doublet.metadata<-list()
doublet.metadata[doublet.rows]<-"doublet"
doublet.metadata[16:length(rownames(training.object@meta.data))]<-"singlets"

training.object[["doublet.ID"]]<-as.character(doublet.metadata)

DimPlot(training.object,group.by = "doublet.ID")

#A1 microglia
#A2 astrocytes
#A3 cancer cells

grep("A1", training.object@meta.data$paper.ident)->microglia.idents
grep("A2", training.object@meta.data$paper.ident)->astrocytes.idents
grep("A3", training.object@meta.data$paper.ident)->cancercells.idents

cellnames<-list()
cellnames[microglia.idents]<-"microglia"
cellnames[astrocytes.idents]<-"astrocytes"
cellnames[cancercells.idents]<-"cancercells"

training.object[["cell.identities"]]<-as.character(cellnames)

DimPlot(training.object,group.by = "cell.identities")

```